version: "2"
services:

  project04:
    build: ./project04/project04/app
    container_name: "addressBook"
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
      image: mysql:5.7
      container_name: "MySQL_Database"
      ports:
        - "33000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./project04/project04/db:/docker-entrypoint-initdb.d/:ro